# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77158d14ba1d28118f1ac5981660d47fa201b7e6557a2bdafb63488f02d28a8bc49582dc274edd69ccbaa44720db8fc3a4b4a0d9c3f5db3a05704fe1184fca14

test:
  secret_key_base: bb96d08d8c2e345053ec5aefd1170e59d0b79b711b3f770ee8361fa701fb2456c6fe0a3bad484903a15d7c5775b5cfb0ebbaebe56a2e833bdca044a180a70a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
